from math import sqrt
file_in = open("root.inp")
file_out = open("root.out", "w")
a = file_in.readline()
b = file_in.readline()
c = file_in.readline()
a = int(a)
b = int(b)
c = int(c)
S = (a**2 + b**2 + c**2)/(a*b*c) + sqrt(a*b*c)
S = str(round(S, 2))
file_out.write(S)
file_in.close()
file_out.close()