a1 = input('Enter a1: ')
a2 = input('Enter a2: ')
a3 = input('Enter a3: ')
b = []
temp = str(a1) + str(a2)
b.append(int(temp))
temp = str(a1) + str(a3)
b.append(int(temp))
temp = str(a2) + str(a1)
b.append(int(temp))
temp = str(a2) + str(a3)
b.append(int(temp))
temp = str(a3) + str(a1)
b.append(int(temp))
temp = str(a3) + str(a2)
b.append(int(temp))
b.sort()
print(*b)