from math import *
file_in = open("root.INP")
file_out = open("root.OUT", "w")
a = file_in.readline()
b = file_in.readline()
c = file_in.readline()
a = int(a)
b = int(b)
c = int(c)
S = (a**a + b**b + c**c)/(a*b*c) + sqrt(a*b*c)
S = str(round(S,2))
file_out.write(S)
file_in.close()
file_out.close()