file_in = open("toanco.inp")
file_out = open("toanco.out", "w")
s = file_in.readline()
s = s.split()
x = int(s[0])
y = int(s[1])
a = int(2*x - y/2)
b = int(y/2 - x)
file_out.write(str(a) + " " + str(b))
file_in.close()
file_out.close()